### ISSUE TITLE
[q] how to get ReMarkable user ID

### ISSUE THREAD

**Issue by utrack** [splitbrain/ReMarkableAPI#20]
Hi, thanks for the detailed writeup!

I see that the token given out by rM is, in fact, a JWT token that has an "auth0-userid" field.
Is it a real user ID that's unique (and same) for every user?

For instance, mine is `auth0|5f634d3c591dce00704a9822`; I don't have a second rM account to see if it's different for other users.

**Comment by theogf** [comment]
Mine would be `cHmHTT7VjfNB19gJtpZMmgpdprVpZ0Ec` so I guess they are unique!
