### ISSUE TITLE
Problem connecting as of today

### ISSUE THREAD

**Issue by ericsfraga** [splitbrain/ReMarkableAPI#9]
I've been using your script since February with no problems at all. Works very well and is indispensable for me as I only have Linux systems.
As of this morning, I get the following error message when I try to use the script to even list the contents of the cloud:
`☠ Client error: POST https://my.remarkable.com/token/user/new resulted in a 403 Forbidden response:`
`You have been signed out. Please update your app to log in again.`
I get the same message if I try to "register" again.  Any suggestions?
Thanks,
eric

**Comment by splitbrain** [comment]
Hmm that sucks. Looks like they changed the API. I don't know when I'll find the time to look into it.

**Comment by ericsfraga** [comment]
Okay, thanks for the quick response. It's very annoying if they have changed the API given how little support (i.e. none) they provide for Linux.

**Comment by sandsmark** [comment]
https://github.com/juruen/rmapi/issues/23#issuecomment-425646220

**Comment by ericsfraga** [comment]
@sandsmark Thank you. I'll have a play with rmapi.
In the meantime, I've updated my own scripts to work well with both usb & wifi connections to the tablet, making sure that I am not dependent on the cloud service.

**Comment by Azeirah** [comment]
The fixes, thanks to the link by @sandsmark were pretty easy to implement. I was able to register, list and download a bunch of my documents using this api by changing the endpoints.

I'll create a PR a little later so you can play with it, but it's really just 2 lines of change based on what the @sandsmark link recommends.

**Comment by ericsfraga** [comment]
Excellent.  Thanks.  I look forward to the PR.

**Comment by michaelmior** [comment]
Submitted a PR myself since I also ran into this. Thanks @sandsmark for a pointer to the fix :)

**Comment by Azeirah** [comment]
Oh uh yeah, sorry, I forgot to actually do the pull-request hahaha damn ;_;

@michaelmior's PR is the same as mine, so thanks for doing my job :x

**Comment by michaelmior** [comment]
@Azeirah No worries :) Just scratching my own itch really.
